import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/layouts/Header";
import { ThemeProvider } from "@/components/Themes/ThemeProvider";
import Providers from "@/lib/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Movie+",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html
			lang="fr"
			suppressHydrationWarning
		>
			<body className={`${inter.className} px-2 min-h-screen flex flex-col items-center gap-12 mb-4`}>
				<Providers>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
					>
						<Header />

						<main className="h-full w-full max-w-screen-2xl flex flex-col gap-14">{children}</main>
					</ThemeProvider>
				</Providers>
			</body>
		</html>
	);
}
