import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/layouts/Header";
import { ThemeProvider } from "@/components/Themes/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Movie+",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="fr">
			<body className={`${inter.className} px-2`}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
				>
					<Header />

					<main className="flex flex-col gap-14 max-w-screen-2xl mx-auto mt-14">{children}</main>
				</ThemeProvider>
			</body>
		</html>
	);
}
